### ISSUE TITLE
Errors occur when modifying the events and using it

### ISSUE THREAD

**Issue by CraftCamp1** [Vecnavium/LobbyItems#2]
**Describe the bug**
setCancelled() has been changed to cancel()
**To Reproduce**
move items in inv or drop items when event was set to false.

**Expected behavior**
not crash the server

**LobbyItems plugin information**

- Plugin Version: [e.g. 1.0.0]
2.0.0

**Screenshots**

**Additional context**

**Comment by Vecnavium** [comment]
Please see if the error has been fixed by downloading the latest version from https://github.com/vecnavium-pm-pl/LobbyItems/releases/tag/v2.0.1
